### ISSUE TITLE
Customized preferences for specific files/paths

### ISSUE THREAD

**Issue by glepretre** [dsbonev/whitespace-normalizer#10]
Hi,

I would like to use the [`"path"` layer](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#example-preferences-json-file) in the Brackets preferences to have a different normalization for specific files.

My use case is about Makefile(s): since it only support tabs as indent, I would like to turn off the 'tab to spaces' feature for these files only.

I tried this in `brackets.json` but it does not seems to work:

    {
        "com.github.dsbonev.WhitespaceNormalizer.enabled": true,
        "com.github.dsbonev.WhitespaceNormalizer.trim": true,
        "com.github.dsbonev.WhitespaceNormalizer.transf": true,
        "com.github.dsbonev.WhitespaceNormalizer.eofnl": true,
        path: {
            "Makefile": {
                "com.github.dsbonev.WhitespaceNormalizer.transf": false
            }
        }
    }

Do you think I could try something else or does it require some changes in your extension to make it work? 

Thanks :wink:

**Comment by dsbonev** [comment]
I have tried for couple of hours to get it working. No success. I am not able to read values from .brackets.json file via several styles of API calls found on the net. Any contributions or working examples are welcomed.

**Comment by glepretre** [comment]
Thanks for having taken on your time to try it, this is not a major issue as I don't edit Makefiles every day :smile:

I have not tried yet @MiguelCastillo 's extension [wsSanitizer](https://github.com/MiguelCastillo/Brackets-wsSanitizer) but it seems to be supporting that, if you want to take a look :wink:

**Comment by dsbonev** [comment]
The referenced extension supports everything this one has as features, I suggest that you use that one instead. Thanks for your interest in improving the projects you use.
