### ISSUE TITLE
Use CRLF at the end of file, instead of LF.

### ISSUE THREAD

**Issue by kenmorechalfant** [dsbonev/whitespace-normalizer#11]
In particular, Git complains about this.

    warning: LF will be replaced by CRLF in [path].
    The file will have its original line endings in your working directory.

I think that there's an option in Git to disable this feature; however, I think it would be nice if this extension could use CRLF's or at least have an option to use them.

I didn't know what CRLF meant until Git gave me that warning. Here's an explanation:
http://blog.codinghorror.com/the-great-newline-schism/

**Comment by dsbonev** [comment]
It looks like you are using Windows machine. It's not about this repository, I believe you will see this same warning when interacting with other repositories too. Try to use smart text editor (Notepad++, Atom, etc.) or configure git to auto-correct line endings for you. Read more about this here:
http://stackoverflow.com/a/1967986/691308
http://stackoverflow.com/a/1250133/691308

**Comment by kenmorechalfant** [comment]
I wasn't working with this repository; I was working with a private project of mine and this extension automatically "ensures newline at file end"; well the newline that it's adding is an LF; thus the default setting for Git complains about it. It's not a big issue but it would be nice if this extension had an option to use CRLF at the end of files instead.

I am using Windows, so by default it SHOULD be CRLF... But with this extension it's inserting LF's, which is default for Linux and OSX.

Does that make sense?

**Comment by dsbonev** [comment]
It makes sense now. Do you experience the same issue without extensions or with similar extensions?
